name: example
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world

  build_skim:
    needs: greeting
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow_failure }}
    container: rootproject/root:${{ matrix.version }}-conda
    strategy:
      matrix:
        version: [6.22.00]
        allow_failure: [false]
        include:
          - version: 6.22.06
            allow_failure: true
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: build
        run: |
          COMPILER=$(root-config --cxx)
          FLAGS=$(root-config --cflags --libs)
          $COMPILER -g -O3 -Wall -Wextra -Wpedantic -o skim skim.cxx $FLAGS
